api_platform:
    title: Astro-Otter API Platform
    version: 2.0.0
    # Mercure integration, remove if unwanted
    mercure: ~
    formats:
        jsonld: ['application/ld+json']
        json: [ 'application/json' ]
#        html: [ 'text/html' ]
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
#        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    mapping:
        paths:
            - '%kernel.project_dir%/src/Model'
            - '%kernel.project_dir%/src/Entity'
    elasticsearch:
        hosts: [ '%env(ELASTICSEARCH_HOST)%' ]
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false

when@prod:
    api_platform:
        enable_docs: false
        enable_entrypoint: false
        enable_swagger_ui: false
