api_platform:
    title: Astro-Otter API Platform
    version: 1.0.0
    # Mercure integration, remove if unwanted
    mercure: ~
    # Good defaults for REST APIs
    formats:
        jsonld: [ 'application/ld+json' ]
    error_formats:        
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    mapping:
        paths: 
            - '%kernel.project_dir%/src/Model'
            - '%kernel.project_dir%/src/Entity'
    elasticsearch:
        hosts: ['%env(ELASTICSEARCH_HOST)%']
