framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name
        prefix_seed: dso
        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu

        default_redis_provider: '%env(resolve:REDIS_URL)%'
        
        # Namespaced pools use the above "app" backend by default
        pools:
            cache.dso_redis:
                adapter: cache.adapter.redis
                default_lifetime: 31536000
                public: false
