controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
#auth_redirection:
#    path: /v2/auth
#    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
#    defaults:
#        route: 'auth'
#        permanent: true
#        keepRequestMethod: true
        
auth:
    path: /auth
    methods: ['POST']

refresh_token:
    path: /token/refresh
